<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

### Exercise 1 (Total recall)

|  **Term**  | **Brief Description**                                       |
|:----------:|-------------------------------------------------------------|
| Subsetting | General term for selecting elements                         |
|  Indexing  | Selecting one element                                       |
|  Slicing   | Selecting a range of elements                               |
|   Masking  | To create a filter to show all true elements in the filter  |

### Exercise 2 (Show me the 'odd' letters)

In [7]:
import numpy as np

In [8]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [11]:
mask = (np_array_2d[:,0].astype(int))%2 != 0        #convert slice to integers before checking for remainder
np_array_2d[mask,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

### Exercise 3

In [12]:
import numpy as np

np_array = np.array([[66, 50, 57, -1, -1],
                    [92, -1, 88, -1, -1],
                    [75, -1, -1, 76, -1],
                    [-1, 51, 87, -1, -1],
                    [71, -1, 67, -1, 69]])

np_array[np_array < 50] = -1        #masking without creating another variable  
np_array[np_array > 50] = 1    
np_array[np_array == 50] = 0  

print(np_array)


[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
