<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [6]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [8]:
np_array[2:5]

array(['c3', 'd4', 'e5'], dtype='<U3')

In [ ]:
py_list[1:6:2]              #start at 1 end at 6 but take steps of 2

['b2', 'd4', 'f6']

In [11]:
py_list[5:2:-1]              #start at 5 end at 2, in steps of -1 (REVERSE)

['f6', 'e5', 'd4']

## 1.2 Arrays only | Subsetting by masking

In [22]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = np_array%2 ==0
np_array[mask]



array([ 2,  4,  6,  8, 10])

In [17]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_array[np_array%2 ==0]

array([ 2,  4,  6,  8, 10])

In [ ]:
mask            #only returns true value in the array 

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

## 1.4 Growing lists

# Some loose ends

## 1.5 Tuples

## 1.6 Be VERY careful when copying

## Footnotes