<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [6]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [8]:
np_array[2:5]

array(['c3', 'd4', 'e5'], dtype='<U3')

In [ ]:
py_list[1:6:2]              #start at 1 end at 6 but take steps of 2

['b2', 'd4', 'f6']

In [11]:
py_list[5:2:-1]              #start at 5 end at 2, in steps of -1 (REVERSE)

['f6', 'e5', 'd4']

## 1.2 Arrays only | Subsetting by masking

In [22]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = np_array%2 ==0
np_array[mask]



array([ 2,  4,  6,  8, 10])

ARRAYS ONLY - SUBSETTING BY MASKING 

In [2]:
import numpy as np 

In [5]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask
np_array[my_mask]       #print elements in the array that are true 

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
np_array[np_array > 3]      #this is w/o creating another variable

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [9]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [10]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

In [17]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_array[np_array%2 ==0]

array([ 2,  4,  6,  8, 10])

In [ ]:
mask            #only returns true value in the array 

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [11]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

what is at position 4

In [14]:
py_list_2d[3]

[4, 'D']

In [13]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

what is the first element at position 4

In [15]:
py_list_2d[3][0]

4

In [17]:
np_array_2d[3, 0]           #syntax for arrays just uses a single pair of [ ]

np.str_('4')

what are the first three elements 

In [18]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [19]:
np_array_2d[:3]


array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

hmmmm.

In [20]:
py_list_2d[:3][0]

[1, 'A']

In [22]:
np_array_2d[:3,0]           #compared to list, gives first element of first 3 tuples 

array(['1', '2', '3'], dtype='<U21')

In [ ]:
np_array_2d[:, 0]           #if u want all the elements 

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

creating a larger list from a smaller one

In [24]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [ ]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x
x=[1]
x+= [2]
x+= [3]
x+= [4]
x
x=[1]
x.append(2)         #append adds to the end of a list 
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [ ]:
x = [1, 2, 3]
x += [4, 5, 6]
x
x=[1, 2, 3]
x.extend([4, 5, 6])         #'+' and extend gives the same result 
x

[1, 2, 3, 4, 5, 6]

In [ ]:
x=[1, 2, 3]
x.append([4, 5, 6])         #append is different 
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

- cannot be changed after creatings and are used between ( )

In [28]:
a=(1, 2, 3)     # Define tuple

In [ ]:
print(a[0])    # Access data

1


In [ ]:
a[0]=-1             # does not work 

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [31]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [35]:
x=[1, 2, 3]         #do this instead
y=x.copy()
z=x.copy()

## Footnotes