<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

Python Lists

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

Numpy Arrays

In [12]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

Dictionary 

In [1]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}
#key value separated by ':'

## 1.2 Accessing data from a list (or array)

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [3]:
py_real_names[0]

'Natasha Romanoff'

In [4]:
py_super_names[0]

'Black Widow'

## 1.3 Accessing data from a dictionary

In [5]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [6]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [7]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [8]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [11]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [12]:
import numpy as np

In [13]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [23]:
print(len(py_list_2d))
print(len(np_array_2d))
np_array_2d.shape

10
10


(10, 2)

## 2.2 Arrays are fussy about type

In [30]:
py_list = [1, 1.5, 'A']
np_array = np.array([py_list])


In [31]:
py_list

[1, 1.5, 'A']

In [ ]:
np_array            #notice the numbers are turned into strings 

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [35]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)            
#Reusing the Python List to create a New Numpy array 

In [40]:
for item in py_list:
    print(item)

1
2
3
4
5


In [30]:
np_array + 10

array([11, 12, 13, 14, 15])

In [ ]:
py_list + 10        # Won't work!(only can concatenate)

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [32]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [ ]:
py_list_1 + py_list_2           # concatenated the lists DID NOT ADD THE NOS.

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [ ]:
np_array_1 + np_array_2         #added the numbers tgt 

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [36]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [38]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [39]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [41]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [42]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [43]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [40]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [44]:
py_list == 3     # Works, but what IS the question? 
# always false because a list cant be equal to 3

False

In [43]:
np_array == 3  


array([False, False,  True, False, False])

In [44]:
np_array > 3 

array([False, False, False,  True,  True])

In [48]:
py_list > 3     #won't work 

TypeError: '>' not supported between instances of 'list' and 'int'

In [46]:
sum(np_array>3)

np.int64(2)

In [45]:
mask = np_array > 3                
np_array[mask]
# one of the most powerful tools, uses it to fish out the numbers from the list


array([4, 5])

## 2.8 Mathematics

In [51]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

to find mean

In [52]:
sum(py_list)/len(py_list)

3.0

In [49]:
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()

np.float64(1.4142135623730951)

## Footnotes